const { MongoClient } = require("mongodb");

const uri = "mongodb://localhost:27017";
const client = new MongoClient(uri);

const students = [
  { lastName: "កាន", firstName: "សីហា", gender: "ប", grade: 1 },
  { lastName: "កុសល់", firstName: "ស្រីរ័ត្ន", gender: "ស", grade: 1 },
  { lastName: "ខេន", firstName: "សុវណ្ណារ៉ា", gender: "ប", grade: 1 },
  { lastName: "គុជ", firstName: "សាឡូម", gender: "ប", grade: 1 },
  { lastName: "ចេន", firstName: "ផានសុផល", gender: "ប", grade: 1 },
  { lastName: "ឆៃ", firstName: "សុខគន្ធា", gender: "ស", grade: 1 },
  { lastName: "ជា", firstName: "ស្រីណែត", gender: "ស", grade: 1 },
  { lastName: "ជ្រាស្រេង", firstName: "ហេងមាន", gender: "ស", grade: 1 },
  { lastName: "ដា", firstName: "វណ្ណឧត្តម", gender: "ប", grade: 1 },
  { lastName: "ណាន", firstName: "សុដាលីន", gender: "ស", grade: 1 },
  { lastName: "ទុំ", firstName: "ទិវា", gender: "ប", grade: 1 },
  { lastName: "ធយ", firstName: "ហាណា", gender: "ស", grade: 1 },
  { lastName: "ធឿន", firstName: "រក្សា", gender: "ស", grade: 1 },
  { lastName: "ធឿន", firstName: "សាន្តណា", gender: "ស", grade: 1 },
  { lastName: "នាថទ្រី", firstName: "វិន្និកា", gender: "ស", grade: 1 },
  { lastName: "ផុន", firstName: "ថៃលី", gender: "ប", grade: 1 },
  { lastName: "ផៃ", firstName: "លក្ខណា", gender: "ស", grade: 1 },
  { lastName: "ពៅ", firstName: "ច័ន្ទសុជាតា", gender: "ស", grade: 1 },
  { lastName: "ភាង", firstName: "សុផាន្នន់", gender: "ប", grade: 1 },
  { lastName: "ភឿន", firstName: "ចាន់ទីន", gender: "ស", grade: 1 },
  { lastName: "ម៉េង", firstName: "ភារុណ", gender: "ប", grade: 1 },
  { lastName: "ម៉ែន", firstName: "ខេមរិន", gender: "ប", grade: 1 },
  { lastName: "យន់", firstName: "ឌីឧត្ដម", gender: "ប", grade: 1 },
  { lastName: "រស់", firstName: "មុន្នីបុស្បា", gender: "ស", grade: 1 },
  { lastName: "រ៉សាក់", firstName: "សូមីរ៉ា", gender: "ស", grade: 1 },
  { lastName: "រ៉េត", firstName: "រិទ្ធី", gender: "ប", grade: 1 },
  { lastName: "រីឡា", firstName: "សុខលាង", gender: "ប", grade: 1 },
  { lastName: "វ៉ន", firstName: "ចិនមករា", gender: "ប", grade: 1 },
  { lastName: "វិទូ", firstName: "សត្រា", gender: "ប", grade: 1 },
  { lastName: "វិបុល", firstName: "សេរីវឌ្ឍនៈ", gender: "ប", grade: 1 },
  { lastName: "ស៊ត់", firstName: "វេហា", gender: "ប", grade: 1 },
  { lastName: "សល់", firstName: "ម៉ីលីកា", gender: "ស", grade: 1 },
  { lastName: "ស៊ង", firstName: "ស័ក្កមុន្នីបញ្ញា", gender: "ប", grade: 1 },
  { lastName: "ស៊ាន", firstName: "សូនីតា", gender: "ស", grade: 1 },
  { lastName: "ស៊ីធា", firstName: "អេលីស", gender: "ស", grade: 1 },
  { lastName: "សា", firstName: "ម៉ីឆិង", gender: "ស", grade: 1 },
  { lastName: "សាំង", firstName: "ធីធាន", gender: "ប", grade: 1 },
  { lastName: "សាំង", firstName: "ធីធីង", gender: "ប", grade: 1 },
  { lastName: "សួយ", firstName: "សេងហ៊ាង", gender: "ប", grade: 1 },
  { lastName: "ហ៊ឹម", firstName: "សិរីវឌ្ឍនា", gender: "ស", grade: 1 },
  { lastName: "ហ៊ៅ", firstName: "ភ័ក្រវឌ្ឍនា", gender: "ប", grade: 1 },
  { lastName: "ហេង", firstName: "សុវណ្ណភាឫទ្ធិ", gender: "ប", grade: 1 },
  { lastName: "ឡូត", firstName: "ស៊ីវលី", gender: "ស", grade: 1 },
  { lastName: "ឡេង", firstName: "សុខរក្សា", gender: "ប", grade: 1 },
  { lastName: "អ៊ីង", firstName: "ចិត្រា", gender: "ប", grade: 1 },
  { lastName: "កាយ", firstName: "គឺមហាក់", gender: "ប", grade: 1 },
  { lastName: "កេន", firstName: "ចាន់ឌី", gender: "ប", grade: 1 },
  { lastName: "ខុម", firstName: "មុន្នីរតនៈ", gender: "ប", grade: 1 },
  { lastName: "គិត", firstName: "ក័ញ្ចនា", gender: "ស", grade: 1 },
  { lastName: "គឹមសេង", firstName: "សក្កណា", gender: "ស", grade: 1 },
  { lastName: "ឆុត", firstName: "និមល", gender: "ស", grade: 1 },
  { lastName: "ឈឿន", firstName: "សាសូម៉ា", gender: "ស", grade: 1 },
  { lastName: "ឈឿម", firstName: "រស្មី", gender: "ស", grade: 1 },
  { lastName: "ដា", firstName: "វ៉ាយូ", gender: "ប", grade: 1 },
  { lastName: "ធា", firstName: "ហ៊ុយណេង", gender: "ស", grade: 1 },
  { lastName: "បូ", firstName: "ចាន់រ៉ាឌីន", gender: "ប", grade: 1 },
  { lastName: "ផល", firstName: "ពេជ្រចរិយា", gender: "ស", grade: 1 },
  { lastName: "ពឹង", firstName: "ឡាយណា", gender: "ស", grade: 1 },
  { lastName: "ពេជ្រ", firstName: "ដារីយា", gender: "ស", grade: 1 },
  { lastName: "ភាក់", firstName: "គឹមឆេង", gender: "ស", grade: 1 },
  { lastName: "ម៉ន", firstName: "សាម៉េត", gender: "ប", grade: 1 },
  { lastName: "យ៉ុង", firstName: "អេស្ទ័រ", gender: "ស", grade: 1 },
  { lastName: "រឿម", firstName: "រតនា", gender: "ប", grade: 1 },
  { lastName: "សេង", firstName: "លីហៀង", gender: "ប", grade: 1 },
  { lastName: "ហ៊ាន", firstName: "គឹមហុក", gender: "ប", grade: 1 },
  { lastName: "ឡែន", firstName: "ស្រីរ័ត្ន", gender: "ស", grade: 1 },
  { lastName: "អុន", firstName: "ដេវីត", gender: "ប", grade: 1 },
  { lastName: "សីហា", firstName: "សុវណ្ណរតនា", gender: "ប", grade: 1 },
  { lastName: "វ័ន្ត", firstName: "វ៉ាយុ", gender: "ប", grade: 1 },
  { lastName: "យ៉ង់", firstName: "ស៊ីយីម", gender: "ស", grade: 1 },
  { lastName: "សាន", firstName: "សុផាណា", gender: "ស", grade: 1 },
  { lastName: "ពេជ្រ", firstName: "ផានិត", gender: "ប", grade: 1 },
  { lastName: "សុផាន់ណា", firstName: "កាន់នីកា", gender: "ស", grade: 1 },
  { lastName: "សន", firstName: "វីរ:", gender: "ប", grade: 1 },
  { lastName: "អាត", firstName: "សំណាង", gender: "ប", grade: 1 },
  { lastName: "ហេង", firstName: "ម៉ូលីកា", gender: "ស", grade: 1 },
  { lastName: "សៀក", firstName: "ច័ន្ទចេស្តា", gender: "ប", grade: 1 },
  { lastName: "រ៉ាត់", firstName: "សុគន្ធារី", gender: "ស", grade: 1 },
  { lastName: "នី", firstName: "សំណាង", gender: "ប", grade: 1 },
  { lastName: "សុង", firstName: "សុភីណៃ", gender: "ប", grade: 1 },
  { lastName: "លី", firstName: "ម៉េងលាភ", gender: "ប", grade: 1 },
  { lastName: "សុខ", firstName: "រាំបូរ", gender: "ប", grade: 1 },
  { lastName: "ស៊ាន", firstName: "រតនះ", gender: "ប", grade: 1 },
  { lastName: "ឆើត", firstName: "សុមានីតា", gender: "ស", grade: 1 },
  { lastName: "ឆេត", firstName: "គឹមឆៀង", gender: "ប", grade: 1 },
  { lastName: "ជុំ", firstName: "វីរៈបុត្រ", gender: "ប", grade: 1 },
  { lastName: "ជួប", firstName: "ឦស", gender: "ប", grade: 1 },
  { lastName: "ឈង់", firstName: "ចន្ទគ្រឹស្នា", gender: "ប", grade: 1 },
  { lastName: "ឈួរ", firstName: "សុវណ្ណារាជ", gender: "ប", grade: 1 },
  { lastName: "ថា", firstName: "រ៉ានុត", gender: "ប", grade: 1 },
  { lastName: "ទិត្យ", firstName: "សុខរក្សា", gender: "ស", grade: 1 },
  { lastName: "ធឿន", firstName: "ឆានុន", gender: "ប", grade: 1 },
  { lastName: "បណ្ដូល", firstName: "សម្បត្តិវិជ្ជា", gender: "ប", grade: 1 },
  { lastName: "ផល្លា", firstName: "សុខលីម៉េង", gender: "ស", grade: 1 },
  { lastName: "ផាង", firstName: "ហ៊ាងហេង", gender: "ប", grade: 1 },
  { lastName: "ផានិត", firstName: "ថៃណាំ", gender: "ប", grade: 1 },
  { lastName: "ផូ", firstName: "ម៉ាទីន", gender: "ប", grade: 1 },
  { lastName: "ម៉ូ", firstName: "វីរ:បុត្រ", gender: "ប", grade: 1 },
  { lastName: "ម៉ៃ", firstName: "សុធីតា", gender: "ស", grade: 1 },
  { lastName: "មុន្នី", firstName: "ករុណា", gender: "ប", grade: 1 },
  { lastName: "យី", firstName: "គូហ្សា", gender: "ស", grade: 1 },
  { lastName: "រតនៈនេត", firstName: "សុខចេស្តា", gender: "ប", grade: 1 },
  { lastName: "រស្មី", firstName: "ម៉ូនីកា", gender: "ស", grade: 1 },
  { lastName: "រិទ្ធី", firstName: "សុវណ្ណដារិទ្ធិ", gender: "ប", grade: 1 },
  { lastName: "រុំ", firstName: "រតនៈ", gender: "ប", grade: 1 },
  { lastName: "លីវាំន់", firstName: "លីឈិញ", gender: "ស", grade: 1 },
  { lastName: "លឹម", firstName: "ឈៀងម៉ៃ", gender: "ស", grade: 1 },
  { lastName: "ស៊ាង", firstName: "ចាន់វាសនា", gender: "ប", grade: 1 },
  { lastName: "ស៊ុយ", firstName: "យូវីន", gender: "ប", grade: 1 },
  { lastName: "សុវណ្ណ", firstName: "អរិយាអម្ពរ", gender: "ស", grade: 1 },
  { lastName: "សៀង", firstName: "សុលាប", gender: "ស", grade: 1 },
  { lastName: "សែន", firstName: "មករា", gender: "ប", grade: 1 },
  { lastName: "សែន", firstName: "វណ្ណប្រាយុទ្ធ", gender: "ប", grade: 1 },
  { lastName: "ហ៊ាត", firstName: "រស្មី", gender: "ស", grade: 1 },
  { lastName: "ហ៊ាន", firstName: "លីហ្សា", gender: "ស", grade: 1 },
  { lastName: "ហូរ", firstName: "ស្រីពេជ្រ", gender: "ស", grade: 1 },
  { lastName: "ហួរ", firstName: "សុលាភ", gender: "ប", grade: 1 },
  { lastName: "ហេង", firstName: "រស្មី", gender: "ប", grade: 1 },
  { lastName: "ហៃ", firstName: "ម៉ីជូ", gender: "ស", grade: 1 },
  { lastName: "ហៃ", firstName: "ស៊ុនចេង", gender: "ប", grade: 1 },
  { lastName: "ឡង", firstName: "សៀវឡុង", gender: "ប", grade: 1 },
  { lastName: "ឡោះ", firstName: "ម៉ារី", gender: "ស", grade: 1 },
  { lastName: "អួន", firstName: "សុវណ្ណអេលីណា", gender: "ស", grade: 1 },
  { lastName: "ម៉ូ", firstName: "ម៉ាលីយ៉ា", gender: "ស", grade: 1 },
  { lastName: "អឿន", firstName: "សុភី", gender: "ប", grade: 1 },
  { lastName: "សៅ", firstName: "អុីសា", gender: "ស", grade: 1 },
  { lastName: "ឃន", firstName: "លីធាង", gender: "ប", grade: 1 },
  { lastName: "ឃឹម", firstName: "ស្រីណុច", gender: "ស", grade: 1 },
  { lastName: "ចាន់", firstName: "សុម៉ាលីន", gender: "ស", grade: 1 },
  { lastName: "ជាចិន", firstName: "មុនិន្ទកិត្យា", gender: "ប", grade: 1 },
  { lastName: "ជុល", firstName: "ជូស៊ាង", gender: "ប", grade: 1 },
  { lastName: "ឈាង", firstName: "ឈីឈី", gender: "ស", grade: 1 },
  { lastName: "ឌី", firstName: "សីហា", gender: "ប", grade: 1 },
  { lastName: "ឌឿន", firstName: "សុជាស្រ៊ុនសុវណ្ណា", gender: "ប", grade: 1 },
  { lastName: "ណែម", firstName: "មុនីឧត្តម", gender: "ប", grade: 1 },
  { lastName: "ថា", firstName: "មួយស៊ាង", gender: "ស", grade: 1 },
  { lastName: "ធឿន", firstName: "ម៉ាណូ", gender: "ប", grade: 1 },
  { lastName: "នី", firstName: "រ៉ាវី", gender: "ប", grade: 1 },
  { lastName: "នឿន", firstName: "សុខរាជ", gender: "ប", grade: 1 },
  { lastName: "ប៉ុល", firstName: "សុវណ្ណមុនីឧត្តម", gender: "ប", grade: 1 },
  { lastName: "ភារ៉ា", firstName: "ដារារាជ", gender: "ប", grade: 1 },
  { lastName: "ម៉េន", firstName: "ម៉េងជីង", gender: "ស", grade: 1 },
  { lastName: "យ៉ម", firstName: "វិជ្ជា", gender: "ប", grade: 1 },
  { lastName: "រ៉ាន", firstName: "វឌ្ឍនា", gender: "ស", grade: 1 },
  { lastName: "រិន", firstName: "នរៈ", gender: "ប", grade: 1 },
  { lastName: "រិន", firstName: "សុវណ្ណដាលីស", gender: "ស", grade: 1 },
  { lastName: "រ័ត្ន", firstName: "ឧត្តមមុនី", gender: "ប", grade: 1 },
  { lastName: "វ៉ា", firstName: "គឹមឈី", gender: "ស", grade: 1 },
  { lastName: "វីន", firstName: "គីមឈុន", gender: "ប", grade: 1 },
  { lastName: "សង់", firstName: "ស៊ីស៊ាន", gender: "ប", grade: 1 },
  { lastName: "សាន", firstName: "រីយ៉ា", gender: "ស", grade: 1 },
  { lastName: "សាវៃ", firstName: "សុកញ្ចានា", gender: "ស", grade: 1 },
  { lastName: "សីហា", firstName: "នរៈសត្យា", gender: "ប", grade: 1 },
  { lastName: "សុខនីម", firstName: "ប៉ាវីវ៉ាត់", gender: "ប", grade: 1 },
  { lastName: "សុភ័ន្ត", firstName: "មនោវឌ្ឍនា", gender: "ស", grade: 1 },
  { lastName: "សំ", firstName: "សម្បត្តិបញ្ញា", gender: "ប", grade: 1 },
  { lastName: "ហាំង", firstName: "សុបញ្ញា", gender: "ប", grade: 1 },
  { lastName: "ហឿត", firstName: "ស៊ុនលី", gender: "ប", grade: 1 },
  { lastName: "ហេង", firstName: "ប្រសិទ្ធបញ្ញា", gender: "ប", grade: 1 },
  { lastName: "ហេង", firstName: "ពុតសិទ្ធិកា", gender: "ស", grade: 1 },
  { lastName: "ឯក", firstName: "ហេងម៉ីអ៊ីង", gender: "ស", grade: 1 },
  { lastName: "ជា", firstName: "សំណាង", gender: "ប", grade: 1 },
  { lastName: "ផល", firstName: "បញ្ញា", gender: "ប", grade: 1 },
  { lastName: "ផល", firstName: "ស្រីកា", gender: "ស", grade: 1 },
  { lastName: "ហេង", firstName: "ប៊ុនហុង", gender: "ប", grade: 1 },
];

async function run() {
  try {
    await client.connect();
    const db = client.db("school_db");
    const collection = db.collection("students");
    const result = await collection.insertMany(students);
    console.log(`✅ Inserted ${result.insertedCount} students`);
  } catch (err) {
    console.error("❌ Error:", err);
  } finally {
    await client.close();
  }
}

run();
